### ISSUE TITLE
Merge into GitHub's `hub` CLI?

### ISSUE THREAD

**Issue by jedwards1211** [mbrookes/git-pull-request#2]
This is cool but I recently discovered [`hub`, GitHub's elegant CLI!](https://hub.github.com/)

However, your package seems much more convenient and full-featured for managing PRs.  `hub` requires the full URL:

```
# check out a pull request for review
$ git checkout https://github.com/github/hub/pull/134
→ (creates a new branch with the contents of the pull request)
```

I think it would be great if we could merge all of the features you have here into `hub`, using `pr` as a subcommand (since `hub` is basically a proxy for `git` that adds extra features):

```
git pr pull 134
git pr branch 134
git pr -d 134
```
etc...

**Comment by mbrookes** [comment]
The reason gpr doesn't need the full URL is because it reads it from package.json, so for non-node projects you have to create a minimal one, as per the README. Thinking about it though, it should be possible to get that from the .git remote config file.

It wouldn't be so much a merge as a port of the features, since this is written in node, and hub is written in go. You're more than welcome to do just that if you're a go person.

**Comment by jedwards1211** [comment]
Oh, heh...I didn't think about what language hub is written in.  Ain't got time for that 😇
